##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-applets
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - libcpupower-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtksourceview-3.0-dev
    - libgtop2-dev
    - libgucharmap-2-90-dev
    - libiw-dev
    - libmate-panel-applet-dev
    - libmateweather-dev
    - libnotify-dev
    - libpolkit-gobject-1-dev
    - libupower-glib-dev
    - libwnck-3-dev
    - libx11-dev
    - libxml2-dev
    - make
    - mate-common
    - x11proto-kb-dev
    - yelp-tools

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/mate-desktop/mate-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/mate-applets/raw/master/cpufreq/pixmaps/cpufreq-100.png; fi
