#! /bin/sh

PACKAGE=cafe-applets;
ACCESSX=cafe-accessx-status;
BATT=cafe-battstat;
CHAR=cafe-char-palette;
FREQ=cafe-cpufreq-applet;
DRIVE=cafe-drivemount;
GEYES=cafe-geyes;
WEATHER=cafeweather;
MULTI=cafe-multiload;
NET=cafe-netspeed-applet;
STICKY=cafe-stickynotes-applet;
TRASH=cafe-trashapplet;

# main translation
make -C po $PACKAGE.pot && mv po/$PACKAGE.pot .
sed -i "/#, fuzzy/d" $PACKAGE.pot

# accessx-status
make -C accessx-status/docs $ACCESSX.pot \
&& mv accessx-status/docs/$ACCESSX.pot .

# battstat
make -C battstat/docs $BATT.pot \
&& mv battstat/docs/$BATT.pot .

# charpick
make -C charpick/help $CHAR.pot \
&& mv charpick/help/$CHAR.pot .

# cpufreq
make -C cpufreq/help $FREQ.pot \
&& mv cpufreq/help/$FREQ.pot .

# drivemount
make -C drivemount/help $DRIVE.pot \
&& mv drivemount/help/$DRIVE.pot .

# geyes
make -C geyes/docs $GEYES.pot \
&& mv geyes/docs/$GEYES.pot .

# weather
make -C cafeweather/docs $WEATHER.pot \
&& mv cafeweather/docs/$WEATHER.pot .

# multiload
make -C multiload/docs $MULTI.pot \
&& mv multiload/docs/$MULTI.pot .

# netspeed
make -C netspeed/help $NET.pot \
&& mv netspeed/help/$NET.pot .

# stickynotes
make -C stickynotes/docs $STICKY.pot \
&& mv stickynotes/docs/$STICKY.pot .

# trashapplet
make -C trashapplet/docs $TRASH.pot \
&& mv trashapplet/docs/$TRASH.pot .

