name: reusing workflow

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  docker:
    uses: cafe-desktop/cafe-common/.github/workflows/main.yml@deploytest
    with:
      image_name: cafe-applets
      tag: $GITHUB_RUN_NUMBER
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
